services:
  - type: web
    name: prowear-app
    env: node
    plan: starter
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: joytech-neon-db
          property: connectionString
